<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RentPaymentsSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();
        
        $tenants = [8, 9, 10];
        $landlords = [3, 4, 5];
        $properties = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

        $payments = [
            [
                'lease_id' => 1,
                'property_id' => 1,
                'tenant_id' => $tenants[0],
                'landlord_id' => $landlords[0],
                'payment_number' => 'PAY-' . $now->timestamp . '-001',
                'amount' => 1500000,
                'late_fee_amount' => 0,
                'total_amount' => 1500000,
                'payment_method' => 'bank_transfer',
                'transaction_id' => 'TXN-' . strtoupper(uniqid()),
                'period_start' => $now->copy()->subMonths(2)->startOfMonth(),
                'period_end' => $now->copy()->subMonths(2)->endOfMonth(),
                'paid_at' => $now->copy()->subMonths(2)->addDays(5),
                'status' => 'completed',
                'notes' => 'Kodi ya mwezi Januari - Nyumba ya Kisasa Kariakoo',
                'created_at' => $now->copy()->subMonths(2)->addDays(5),
                'updated_at' => $now->copy()->subMonths(2)->addDays(5),
            ],
            [
                'lease_id' => 1,
                'property_id' => 1,
                'tenant_id' => $tenants[0],
                'landlord_id' => $landlords[0],
                'payment_number' => 'PAY-' . $now->timestamp . '-002',
                'amount' => 1500000,
                'late_fee_amount' => 0,
                'total_amount' => 1500000,
                'payment_method' => 'mobile_money',
                'transaction_id' => 'TXN-' . strtoupper(uniqid()),
                'period_start' => $now->copy()->subMonth()->startOfMonth(),
                'period_end' => $now->copy()->subMonth()->endOfMonth(),
                'paid_at' => $now->copy()->subMonth()->addDays(3),
                'status' => 'completed',
                'notes' => 'Kodi ya mwezi Februari - Nyumba ya Kisasa Kariakoo',
                'created_at' => $now->copy()->subMonth()->addDays(3),
                'updated_at' => $now->copy()->subMonth()->addDays(3),
            ],
            [
                'lease_id' => 2,
                'property_id' => 2,
                'tenant_id' => $tenants[1],
                'landlord_id' => $landlords[0],
                'payment_number' => 'PAY-' . $now->timestamp . '-003',
                'amount' => 350000,
                'late_fee_amount' => 0,
                'total_amount' => 350000,
                'payment_method' => 'cash',
                'transaction_id' => 'TXN-' . strtoupper(uniqid()),
                'period_start' => $now->copy()->subWeeks(3)->startOfMonth(),
                'period_end' => $now->copy()->subWeeks(3)->endOfMonth(),
                'paid_at' => $now->copy()->subWeeks(3)->addDays(2),
                'status' => 'completed',
                'notes' => 'Kodi ya mwezi - Studio Nzuri Mbezi',
                'created_at' => $now->copy()->subWeeks(3)->addDays(2),
                'updated_at' => $now->copy()->subWeeks(3)->addDays(2),
            ],
            [
                'lease_id' => 3,
                'property_id' => 3,
                'tenant_id' => $tenants[2],
                'landlord_id' => $landlords[1],
                'payment_number' => 'PAY-' . $now->timestamp . '-004',
                'amount' => 2500000,
                'late_fee_amount' => 0,
                'total_amount' => 2500000,
                'payment_method' => 'bank_transfer',
                'transaction_id' => 'TXN-' . strtoupper(uniqid()),
                'period_start' => $now->copy()->subMonths(3)->startOfMonth(),
                'period_end' => $now->copy()->subMonths(3)->endOfMonth(),
                'paid_at' => $now->copy()->subMonths(3)->addDays(10),
                'status' => 'completed',
                'notes' => 'Kodi ya mwezi - Gorofa La Posta',
                'created_at' => $now->copy()->subMonths(3)->addDays(10),
                'updated_at' => $now->copy()->subMonths(3)->addDays(10),
            ],
            [
                'lease_id' => 3,
                'property_id' => 3,
                'tenant_id' => $tenants[2],
                'landlord_id' => $landlords[1],
                'payment_number' => 'PAY-' . $now->timestamp . '-005',
                'amount' => 2500000,
                'late_fee_amount' => 0,
                'total_amount' => 2500000,
                'payment_method' => 'mobile_money',
                'transaction_id' => 'TXN-' . strtoupper(uniqid()),
                'period_start' => $now->copy()->subMonths(2)->startOfMonth(),
                'period_end' => $now->copy()->subMonths(2)->endOfMonth(),
                'paid_at' => $now->copy()->subMonths(2)->addDays(8),
                'status' => 'completed',
                'notes' => 'Kodi ya mwezi - Gorofa La Posta',
                'created_at' => $now->copy()->subMonths(2)->addDays(8),
                'updated_at' => $now->copy()->subMonths(2)->addDays(8),
            ],
            [
                'lease_id' => 4,
                'property_id' => 4,
                'tenant_id' => $tenants[0],
                'landlord_id' => $landlords[2],
                'payment_number' => 'PAY-' . $now->timestamp . '-006',
                'amount' => 2000000,
                'late_fee_amount' => 0,
                'total_amount' => 2000000,
                'payment_method' => 'bank_transfer',
                'transaction_id' => 'TXN-' . strtoupper(uniqid()),
                'period_start' => $now->copy()->subMonth()->startOfMonth(),
                'period_end' => $now->copy()->subMonth()->endOfMonth(),
                'paid_at' => $now->copy()->subMonth()->addDays(15),
                'status' => 'completed',
                'notes' => 'Kodi ya mwezi - Nyumba ya Familia Kijitonyama',
                'created_at' => $now->copy()->subMonth()->addDays(15),
                'updated_at' => $now->copy()->subMonth()->addDays(15),
            ],
            [
                'lease_id' => 5,
                'property_id' => 5,
                'tenant_id' => $tenants[1],
                'landlord_id' => $landlords[1],
                'payment_number' => 'PAY-' . $now->timestamp . '-007',
                'amount' => 1200000,
                'late_fee_amount' => 0,
                'total_amount' => 1200000,
                'payment_method' => 'mobile_money',
                'transaction_id' => 'TXN-' . strtoupper(uniqid()),
                'period_start' => $now->copy()->subWeeks(2)->startOfMonth(),
                'period_end' => $now->copy()->subWeeks(2)->endOfMonth(),
                'paid_at' => $now->copy()->subWeeks(2)->addDays(5),
                'status' => 'completed',
                'notes' => 'Kodi ya mwezi - Flat la Kisasa Njiro',
                'created_at' => $now->copy()->subWeeks(2)->addDays(5),
                'updated_at' => $now->copy()->subWeeks(2)->addDays(5),
            ],
            [
                'lease_id' => 6,
                'property_id' => 7,
                'tenant_id' => $tenants[2],
                'landlord_id' => $landlords[2],
                'payment_number' => 'PAY-' . $now->timestamp . '-008',
                'amount' => 3500000,
                'late_fee_amount' => 0,
                'total_amount' => 3500000,
                'payment_method' => 'bank_transfer',
                'transaction_id' => 'TXN-' . strtoupper(uniqid()),
                'period_start' => $now->copy()->subWeek()->startOfMonth(),
                'period_end' => $now->copy()->subWeek()->endOfMonth(),
                'paid_at' => $now->copy()->subWeek()->addDays(3),
                'status' => 'completed',
                'notes' => 'Kodi ya mwezi - Villa ya Kifahari Mbezi',
                'created_at' => $now->copy()->subWeek()->addDays(3),
                'updated_at' => $now->copy()->subWeek()->addDays(3),
            ],
            [
                'lease_id' => 7,
                'property_id' => 8,
                'tenant_id' => $tenants[0],
                'landlord_id' => $landlords[1],
                'payment_number' => 'PAY-' . $now->timestamp . '-009',
                'amount' => 800000,
                'late_fee_amount' => 0,
                'total_amount' => 800000,
                'payment_method' => 'cash',
                'transaction_id' => 'TXN-' . strtoupper(uniqid()),
                'period_start' => $now->copy()->subDays(10)->startOfMonth(),
                'period_end' => $now->copy()->subDays(10)->endOfMonth(),
                'paid_at' => $now->copy()->subDays(10),
                'status' => 'completed',
                'notes' => 'Kodi ya mwezi - Nyumba Ndogu Dodoma',
                'created_at' => $now->copy()->subDays(10),
                'updated_at' => $now->copy()->subDays(10),
            ],
            [
                'lease_id' => 1,
                'property_id' => 1,
                'tenant_id' => $tenants[0],
                'landlord_id' => $landlords[0],
                'payment_number' => 'PAY-' . $now->timestamp . '-010',
                'amount' => 1500000,
                'late_fee_amount' => 0,
                'total_amount' => 1500000,
                'payment_method' => 'mobile_money',
                'transaction_id' => null,
                'period_start' => $now->copy()->startOfMonth(),
                'period_end' => $now->copy()->endOfMonth(),
                'paid_at' => null,
                'status' => 'pending',
                'notes' => 'Kodi ya mwezi Machi - Nyumba ya Kisasa Kariakoo',
                'created_at' => $now->copy()->subDays(2),
                'updated_at' => $now->copy()->subDays(2),
            ],
            [
                'lease_id' => 4,
                'property_id' => 4,
                'tenant_id' => $tenants[0],
                'landlord_id' => $landlords[2],
                'payment_number' => 'PAY-' . $now->timestamp . '-011',
                'amount' => 2000000,
                'late_fee_amount' => 0,
                'total_amount' => 2000000,
                'payment_method' => 'bank_transfer',
                'transaction_id' => null,
                'period_start' => $now->copy()->addMonth()->startOfMonth(),
                'period_end' => $now->copy()->addMonth()->endOfMonth(),
                'paid_at' => null,
                'status' => 'pending',
                'notes' => 'Kodi ya mwezi - Nyumba ya Familia Kijitonyama',
                'created_at' => $now->copy()->subDays(1),
                'updated_at' => $now->copy()->subDays(1),
            ],
            [
                'lease_id' => 5,
                'property_id' => 5,
                'tenant_id' => $tenants[1],
                'landlord_id' => $landlords[1],
                'payment_number' => 'PAY-' . $now->timestamp . '-012',
                'amount' => 1200000,
                'late_fee_amount' => 0,
                'total_amount' => 1200000,
                'payment_method' => 'mobile_money',
                'transaction_id' => null,
                'period_start' => $now->copy()->addMonth()->startOfMonth(),
                'period_end' => $now->copy()->addMonth()->endOfMonth(),
                'paid_at' => null,
                'status' => 'pending',
                'notes' => 'Kodi ya mwezi - Flat la Kisasa Njiro',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('rent_payments')->insert($payments);

        $this->command->info('Rent payments seeded successfully: ' . count($payments) . ' payments created.');
    }
}
